version: "3.8"

# ──────────────────────────────────────────────
# Docker Compose + Swarm Stack
# Запуск в Swarm:
#   docker stack deploy -c docker-compose.yml ranobe
# ──────────────────────────────────────────────

services:
  ranobe-backend:
    image: test:lastes
    build:
      context: .
      dockerfile: Dockerfile

    ports:
      - "2467:8080"

    networks:
      - ranobe-net
    # ── Swarm Deploy ────────────────────────
    deploy:
      mode: replicated
      replicas: 1

      # placement:
      #   constraints:
      #     - node.role == manager

# ──────────────────────────────────────────────

# ──────────────────────────────────────────────
# Networks
# ──────────────────────────────────────────────
networks:
  ranobe-net:
    driver: overlay
    attachable: true
