// @generated by protoc-gen-connect-es v1.6.1 with parameter "target=ts"
// @generated from file document.proto (package doc, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import {
  DocumentRequest,
  AWSPutRequest,
  AWSPutResponse,
  CreateDocumetnRequest,
  EditDocumentRequest,
} from "./gen/document_pb";
import { MethodKind } from "@bufbuild/protobuf";

/**
 * @generated from service doc.DocumentReadService
 */
export const DocumentReadService = {
  typeName: "doc.DocumentReadService",
  methods: {
    /**
     * @generated from rpc doc.DocumentReadService.Read
     */
    read: {
      name: "Read",
      I: DocumentRequest,
      O: Document,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc doc.DocumentReadService.GetAws
     */
    getAws: {
      name: "GetAws",
      I: AWSPutRequest,
      O: AWSPutResponse,
      kind: MethodKind.Unary,
    },
  },
} as const;

/**
 * @generated from service doc.DocumentSaveService
 */
export const DocumentSaveService = {
  typeName: "doc.DocumentSaveService",
  methods: {
    /**
     * @generated from rpc doc.DocumentSaveService.Save
     */
    save: {
      name: "Save",
      I: CreateDocumetnRequest,
      O: DocumentRequest,
      kind: MethodKind.Unary,
    },
    /**
     * @generated from rpc doc.DocumentSaveService.Edit
     */
    edit: {
      name: "Edit",
      I: EditDocumentRequest,
      O: DocumentRequest,
      kind: MethodKind.Unary,
    },
  },
} as const;
